# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build pages and raise PR to /prod

on:
  push:
    branches: [ "main" ]

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  raise-pr-to-prod:
    runs-on: ubuntu-latest
    needs: build-pages
    steps:
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: my-built-pages
        path: ./pages
    - name: Echo downloaded path
      run: echo ${{steps.download.outputs.download-path}}
    - name: Display downloaded pages
      run: ls -ltR
      working-directory: ./pages
